---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
- apiGroups:
  - example.example.com
  resources:
  - emails
  - reports
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - example.example.com
  resources:
  - emails/finalizers
  - reports/finalizers
  verbs:
  - update
- apiGroups:
  - example.example.com
  resources:
  - emails/status
  - reports/status
  verbs:
  - get
  - patch
  - update
